### ISSUE TITLE
Can `read_parquet()` apply additional metadata set in `write_parquet()`?

### ISSUE THREAD

**Issue by mrcaseb** [r-lib/nanoparquet#84]
`write_parquet()` allows additional metadata as key-value pairs. I expected those key-value pairs in the attributes of the R object after `read_parquet()` but it seems like I need to access them separately with `parquet_metadata()`? 

I am not familiar with nanoparquet internals but I assume this means two file reads if I would like to apply the meta data as attributes. Can `read_parquet()` directly apply those (additional) meta data as attributes?

``` r
# write parquet and add some meta data
nanoparquet::write_parquet(
  mtcars, 
  "nano.parquet",
  metadata = c("nanoparquet" = as.character(packageVersion("nanoparquet")))
)
# read_parquet does not apply the meta data 
parquet_file <- nanoparquet::read_parquet("nano.parquet")
attributes(parquet_file)
#> $names
#>  [1] "mpg"  "cyl"  "disp" "hp"   "drat" "wt"   "qsec" "vs"   "am"   "gear"
#> [11] "carb"
#> 
#> $row.names
#>  [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
#> [26] 26 27 28 29 30 31 32
#> 
#> $class
#> [1] "tbl"        "data.frame"

# The only way to access meta data is a separate file read with parquet_metadata
meta <- nanoparquet::parquet_metadata("nano.parquet")$file_meta_data$key_value_metadata[[1]]
meta[meta$key != "ARROW:schema", ]
#>           key value
#> 1 nanoparquet 0.3.1
```

<sup>Created on 2024-08-19 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by gaborcsardi** [comment]
I am leaning towards not doing this, for a number of reasons.

One is that I suspect that most people do not need the additional metadata, and it may be confusing to include it. 

This metadata was not part of the original data frame that was saved with `write_parquet()`, either.

`arrow::read_parquet()` also does not read the metadata, and I don't know any reader that does.

True, you need an extra call to read the metadata, but that does not read the whole file, in fact it skips all the data, and only reads the metadata.

**Comment by mrcaseb** [comment]
I am slightly confused because arrow writes and reads object attributes correctly. I know this isn't exactly the same as I did in the above example but nanoparquet also does not use attributes when writing. 

``` r
file_to_save <- mtcars
attr(file_to_save, "nanoparquet") <- as.character(packageVersion("nanoparquet"))

arrow::write_parquet(file_to_save, "arrow.parquet")
arrow_file <- arrow::read_parquet("arrow.parquet")
attributes(arrow_file)
#> $names
#>  [1] "mpg"  "cyl"  "disp" "hp"   "drat" "wt"   "qsec" "vs"   "am"   "gear"
#> [11] "carb"
#> 
#> $row.names
#>  [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
#> [26] 26 27 28 29 30 31 32
#> 
#> $class
#> [1] "tbl_df"     "tbl"        "data.frame"
#> 
#> $nanoparquet
#> [1] "0.3.1"
```

<sup>Created on 2024-08-19 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by gaborcsardi** [comment]
Yes, but these attributes are not simply stored as key-value metadata. If these attributes are important, then Parquet might not be the right file format for the task, because you'll only be able to recover them in R, and Pyarrow, Spark, etc. will ignore them.

Relatedly, I am leaning towards saving arbitrary R objects into Parquet metadata being a bad idea:

```r
file_to_save <- mtcars
attr(file_to_save, "!!!") <- stop
arrow::write_parquet(file_to_save, "arrow.parquet")
attributes(arrow::read_parquet("arrow.parquet"))[["!!!"]]
```

```
#> function (..., call. = TRUE, domain = NULL)
#> {
#>     if (...length() == 1L && inherits(..1, "condition")) {
...
```

**Comment by mrcaseb** [comment]
> you'll only be able to recover them in R, and Pyarrow, DuckDB, Spark, etc. will ignore them

Yep you are right. I forgot about that for a second. It's a special use case where we provide data in different formats for other languages and parquet is supposed to support Python. This issue is resolved for me now.

**Comment by gaborcsardi** [comment]
@torfason Well, if you don't open an issue, then I'll forget about it, probably. :( So if you feel strongly about this, please open an issue.
